### PR TITLE
Replacing legacy Podio service with the frame Podio service

### PR DESCRIPTION
**Pull request by kjvbrt**
Replacing all instances of Podio legacy data service with the new one supporting podio frame.

### CODE REVIEW

**Comment by kjvbrt** [comment]
Fail of stable stack tests expected.

**Comment by BrieucF** [comment]
Hi Juraj, have you checked that the output is still the same when calling the cellID encoding?
Shall we also make changes in k4RecCalorimeter and merge at the same time?

**Comment by kjvbrt** [comment]
The frame related changes to k4RecCalorimeter are already merged. The test `runCaloSim.py` needs one small fix in k4RecCalorimeters. I believe this PR can be safely merged, but first I will overhaul tests in k4Reccalorimeters to be sure.

**Comment by kjvbrt** [comment]
Changed all `FCCDataSvc` to `k4DataSvc` https://github.com/HEP-FCC/k4RecCalorimeter/pull/46.

**Pull request merged**
