### PR TITLE
Fix test environment for spack

### PR DESCRIPTION
**Pull request by vvolkl**

### CODE REVIEW

**Comment by vvolkl** [comment]
```
    it.a9b615891e42539cb991e32a875b20e7ae10f377-dnc4237dvxmgmk7zkgtvd3puwsu4pvki    /spack-src/SimG4Components
  7 "MagFieldFromMap" start time: Feb 08 05:06 CET
  8 Output:
  9 ----------------------------------------------------------
 10 # WARNING: : Module DetComponents.DetComponentsConf not found (needed for co    nfigurable GeoSvc)
 11 Traceback (most recent call last):
 12   File "/cvmfs/sw-nightlies.hsf.org/spackages6/k4fwcore/commit.f4c228b80ffb8    62aaff253a65338ec6a1b836f75/x86_64-centos7-gcc11.2.0-opt/owmtl/bin/k4run", l    ine 34, in <module>
 13     exec(open(f).read())
 14   File "<string>", line 21, in <module>
 15 TypeError: 'NoneType' object is not callable
 16 <end of output>
 17 Test time =   0.12 sec
 18 ------------------------------------------------
```
Hopefully fixes this error in the nightlies

**Comment by kjvbrt** [comment]
Thanks :)

**Comment by tmadlener** [comment]
It looks like they are still broken:
https://gitlab.cern.ch/key4hep/k4-deploy/-/jobs/27533719#L4625

**Comment by andresailer** [comment]
yes
```
# WARNING: : Module SimG4Full.SimG4FullPluginsConf not found (needed for configurable SimG4FullSimActions)
# ERROR: SimG4Svc.actions: Configurable SimG4FullSimActions is not a ConfigurableAlgTool
Traceback (most recent call last):
  File "/cvmfs/sw.hsf.org/spackages6/gaudi/36.5/x86_64-centos7-gcc11.2.0-opt/z2prd/python/GaudiKernel/PropertyProxy.py", line 212, in __get__
    return self.descr.__get__(obj, type)
AttributeError: actions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/sw-nightlies.hsf.org/spackages6/k4fwcore/commit.f4c228b80ffb862aaff253a65338ec6a1b836f75/x86_64-centos7-gcc11.2.0-opt/xi2jt/bin/k4run", line 76, in <module>
    props = conf.getPropertiesWithDescription() #dict propertyname: (propertyvalue, propertydescription)
  File "/cvmfs/sw.hsf.org/spackages6/gaudi/36.5/x86_64-centos7-gcc11.2.0-opt/z2prd/python/GaudiKernel/Configurable.py", line 700, in getPropertiesWithDescription
    props[name] = (proxy.__get__(self), proxy.__doc__)
  File "/cvmfs/sw.hsf.org/spackages6/gaudi/36.5/x86_64-centos7-gcc11.2.0-opt/z2prd/python/GaudiKernel/PropertyProxy.py", line 217, in __get__
    default = self.convertDefaultToBeSet(obj, default)
  File "/cvmfs/sw.hsf.org/spackages6/gaudi/36.5/x86_64-centos7-gcc11.2.0-opt/z2prd/python/GaudiKernel/PropertyProxy.py", line 301, in convertDefaultToBeSet
    raise RuntimeError(
RuntimeError: SimG4Svc.actions: Default configurable for class SimG4FullSimActions not found in ConfigurableDb.CfgDb
<end of output>
Test time =   0.22 sec
```

**Comment by vvolkl** [comment]
Yes, same changes need to be applied to all other Plugins that are created here, at least SimG4FullPlugins. This is  getting somewhat  painful, maybe using the gaudi env script is a better idea?

**Comment by andresailer** [comment]
generator expression with JOIN and a list of targets

**Comment by kjvbrt** [comment]
Might the adding of the missing os import help? https://github.com/HEP-FCC/k4SimGeant4/pull/30

**Comment by andresailer** [comment]
Good guess, but no, still failing.

**Comment by kjvbrt** [comment]
Does it fail the same way as in the morning?

**Comment by andresailer** [comment]
Yes
```
2/2 Testing: MagFieldFromMap
2/2 Test: MagFieldFromMap
Command: "/cvmfs/sw-nightlies.hsf.org/spackages6/k4fwcore/commit.f4c228b80ffb862aaff253a65338ec6a1b836f75/x86_64-centos7-gcc11.2.0-opt/xi2jt/bin/k4run" "/cvmfs/tmp/spack-stage/gitlab-runner/spack-stage-k4simgeant4-commit.920748051476d29c2e9f5c79e3c8bd628bcb0277-eeejzqz24sc3t5b6b63fgbo3g7qks7hq/spack-src/SimG4Components/tests/options/magFieldFromMap.py"
Directory: /cvmfs/tmp/spack-stage/gitlab-runner/spack-stage-k4simgeant4-commit.920748051476d29c2e9f5c79e3c8bd628bcb0277-eeejzqz24sc3t5b6b63fgbo3g7qks7hq/spack-src/SimG4Components
"MagFieldFromMap" start time: Feb 15 14:09 CET
Output:
----------------------------------------------------------
 

# WARNING: : Module SimG4Full.SimG4FullPluginsConf not found (needed for configurable SimG4FullSimActions)
# ERROR: SimG4Svc.actions: Configurable SimG4FullSimActions is not a ConfigurableAlgTool
Traceback (most recent call last):
  File "/cvmfs/sw.hsf.org/spackages6/gaudi/36.5/x86_64-centos7-gcc11.2.0-opt/z2prd/python/GaudiKernel/PropertyProxy.py", line 212, in __get__
    return self.descr.__get__(obj, type)
AttributeError: actions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/sw-nightlies.hsf.org/spackages6/k4fwcore/commit.f4c228b80ffb862aaff253a65338ec6a1b836f75/x86_64-centos7-gcc11.2.0-opt/xi2jt/bin/k4run", line 76, in <module>
    props = conf.getPropertiesWithDescription() #dict propertyname: (propertyvalue, propertydescription)
  File "/cvmfs/sw.hsf.org/spackages6/gaudi/36.5/x86_64-centos7-gcc11.2.0-opt/z2prd/python/GaudiKernel/Configurable.py", line 700, in getPropertiesWithDescription
    props[name] = (proxy.__get__(self), proxy.__doc__)
  File "/cvmfs/sw.hsf.org/spackages6/gaudi/36.5/x86_64-centos7-gcc11.2.0-opt/z2prd/python/GaudiKernel/PropertyProxy.py", line 217, in __get__
    default = self.convertDefaultToBeSet(obj, default)
  File "/cvmfs/sw.hsf.org/spackages6/gaudi/36.5/x86_64-centos7-gcc11.2.0-opt/z2prd/python/GaudiKernel/PropertyProxy.py", line 301, in convertDefaultToBeSet
    raise RuntimeError(
RuntimeError: SimG4Svc.actions: Default configurable for class SimG4FullSimActions not found in ConfigurableDb.CfgDb
<end of output>
Test time =   0.14 sec
```

**Pull request merged**
