### PR TITLE
Upstream and downstream calorimeter energy correction

### PR DESCRIPTION
**Pull request by kjvbrt**
Hello,

This request adds algorithm, which separately sums energy deposited in calorimeter layers and cryostat parts.
The output of the algorithm is used to derive upstream and downstream correction.
Tests were also updated to run with EDM4HEP.
Downstream correction requires enlargement of the back cryostat (pull request in FCCDetectors).

Best,
Juraj

### CODE REVIEW

**Comment by BrieucF** [comment]
Hi @kjvbrt , great thanks! Could you maybe add some more information on what to do after running `EnergyInCaloLayers` ? I mean, how to derive the parameters for the energy dependence and how to actually apply the correction.

Could you also link here the presentation you gave on this topic?

**Comment by BrieucF** [comment]
Tested it for the energy dependence of the upstream correction and everything looks good to me! Do we wait to have the algorithm that apply the correction on the cluster or do we do it in a separated PR?

**Comment by kjvbrt** [comment]
The algorithm for application of the correction should go into k4RecCalorimeter, no?

**Comment by BrieucF** [comment]
Yes indeed it fits better the reco side!
+1

**Review by BrieucF — APPROVED** [review]

**Comment by BrieucF** [comment]
Just for reference, adding here the presentations related to this PR:
 - [March 2021](https://indico.cern.ch/event/1014834/contributions/4270207/attachments/2206067/3732476/energy_corr_2021_mar_11.pdf)
 - [April 2021](https://indico.cern.ch/event/1028898/contributions/4322008/attachments/2226812/3772201/energy_corr_2021_apr_15.pdf)

**Pull request merged**
