### PR TITLE
Propagating mag. field defined in compact file + MagFieldScanner

### PR DESCRIPTION
**Pull request by kjvbrt**
Usage of the `MagFieldTool` in the steering file:
Create a field:
```
# Magnetic field
from Configurables import SimG4MagneticFieldTool
field = SimG4MagneticFieldTool("MagneticFieldTool")
field.FieldOn = True
field.IntegratorStepper = "ClassicalRK4"
```
and provide it to the `SimG4Svc`:
```
geantservice.magneticField = field
```

Usage of the `MagFieldScanner`:
```
# Magnetic field probes
from Configurables import MagFieldScanner
magfieldscanner = MagFieldScanner("MagFieldScanner")
magfieldscanner.outFilePath = "hello.root"
magfieldscanner.xyPlaneProbes = [
#   xMax,    yMax, z
    [160*cm, 1600, 0],
    [1600, 1600, -100],
]
magfieldscanner.zPlaneProbes = [
#   zMin,     zMax,  rMax,   phi (angle from x-axis, in radians)
    [-20.1*m, 20100, 160*cm, 1.57079632679],
]
magfieldscanner.tubeProbes = [
#   zMin,     zMax,  r
    [-20.1*m, 20100, 0], 
]
ApplicationMgr().ExtSvc += [magfieldscanner]
```
`MagFieldScanner` provides three "probe" types:
* `XYPlane`: shows mag. field on the XY plane at any z
* `ZPlane`: shows mag. field on the plane lying on z-axis, at any phi (angle from x-axis)
* `Tube`: shows mag. field on a tube with radius r

### CODE REVIEW

**Comment by BrieucF** [comment]
Hi Juraj, this is very nice, thanks! Can you add a test? 

Maybe worth adding that the customer for this tool is `SimG4Svc`, through the [magneticField](https://github.com/HEP-FCC/k4SimGeant4/blob/main/SimG4Components/src/SimG4Svc.cpp#L23) property.

**Comment by BrieucF** [comment]
Could also maybe show some validation? Like running one low Pt muon gun event with [this config](https://github.com/BrieucF/k4RecTracker/blob/master/Tracking/test/runGenFitTrackingOnSimplifiedDriftChamber.py) with/without 2 Tesla magnetic field and show `events->Draw("simTrackerHits.position.x:simTrackerHits.position.y")` in both cases?

**Comment by kjvbrt** [comment]
Adding three probe plots
tube
xyplane
zplane

**Comment by aciarma** [comment]
Actually, again on the apparent asymmetry, how is the magnetic field passed to the simulation at the very end, via a position-dependent formula or a field map? If a field map is used, could it be due to the cell size?

**Comment by BrieucF** [comment]
Hi Andrea, I am not sure I understand fully what you are trying to achieve but I would not expect DD4hep multipole modeling to be as precise as what comes out of a dedicated tool. Can't you generate the field map from the screens in a dedicated tool, and then import it in DD4hep by providing the map itself? It could then be overlayed with the detector solenoid one.

**Comment by aciarma** [comment]
As Juraj suggested is more likely to be an issue at DD4hep level. I can live with that, as long as I know what the difference is. I have no way of producing a detailed field map. For the moment it is way easier like this, I just wanted to point out this discrepancy for reference.

**Pull request merged**
